-
  name: Install and start nginx
  hosts: linuxweb
  become: true
  tasks:
    - name: Ping all hosts
      ping:

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes